package com.wos.dao.mapper;

import java.util.List;

import com.wos.pojo.AddressType;
public interface AddressTypeMapper {
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_base_AddressType
     *
     * @mbggenerated Thu Nov 27 14:21:43 CST 2014
     */
    int insert(AddressType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_base_AddressType
     *
     * @mbggenerated Thu Nov 27 14:21:43 CST 2014
     */
    int insertSelective(AddressType record);
    
    
    List<AddressType> getAllAddressTypes(String code);
}